exchangeRateURL: https://v6.exchangerate-api.com/v6/f40ba9794464d382433580d9/latest/BYN

spring:
  datasource:
    password: 72305
    url: jdbc:postgresql://localhost:5432/currency
    username: postgres